wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.0
    start_time: 1650530804
    t:
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      3:
      - 2
      - 19
      4: 3.8.0
      5: 0.12.11
      8:
      - 1
      - 2
      - 5
batch_size:
  desc: null
  value: 16
bert_path:
  desc: null
  value: roberta-base
epochs:
  desc: null
  value: 5
exam_name:
  desc: null
  value: roberta-forwardUt
lr:
  desc: null
  value: 2.0e-05
max_seq_len:
  desc: null
  value: 400
max_turn:
  desc: null
  value: 3
momentum:
  desc: null
  value: 0.1
no_cuda:
  desc: null
  value: false
test_batch_size:
  desc: null
  value: 64
